name: build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Python 2.7.7
        run: |
          sudo apt-get install build-essential checkinstall
          sudo apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

          cd $HOME
          wget https://www.python.org/ftp/python/2.7.7/Python-2.7.7.tgz

          tar -xvf Python-2.7.7.tgz
          cd Python-2.7.7
          ./configure
          make
          sudo checkinstall
      - name: Cd to repo path
        run: cd $GITHUB_WORKSPACE
      - name: Clone repo
        uses: actions/checkout@master
      - name: Build recent-stat
        run: python build.py
